### ISSUE TITLE
Use the format contribution API

### ISSUE THREAD

**Issue by aeschli** [FabianLauer/vs-code-xml-format#1]
Instead of adding a new commend, better add yourself as a formatter provider

```
vscode.languages.registerDocumentFormattingEditProvider('xml', ...)
vscode.languages.registerDocumentRangeFormattingEditProvider('xml', ...)
```

Yes then get invoked on the built-in Format command.

You can have a look at my css formatter extension:
https://github.com/aeschli/vscode-css-formatter/

**Comment by FabianLauer** [comment]
Thanks for the hint 👍 Added.
