### ISSUE TITLE
Comments are being removed

### ISSUE THREAD

**Issue by alefragnani** [FabianLauer/vs-code-xml-format#3]
First of all, great extension! :+1: 

If you have comments inside the XML file, they are removed. It doesn't matter if the comments are _commented nodes_ or simply _simple comments_.

Thanks in advance.

**Comment by lelong37** [comment]
+10

**Comment by FabianLauer** [comment]
This should be fixed with version 0.1.1. Just update the extension via VS Code and you're good.
BTW, sorry to keep you guys waiting. Had a bunch of things on my plate, one of them was to build an XML parser that can process all kinds of XML nodes 😉
