### ISSUE TITLE
limit line length

### ISSUE THREAD

**Issue by samba2** [FabianLauer/vs-code-xml-format#5]
I have a tag which as many attributes. Currently this is formatted to one long line where I have to scroll for reading the whole thing. It would be nice if the formatter could break the line into multiple ones.
### Example

Current result after formatting:

```
<View controllerName="opensap.manageproducts.controller.Object" xmlns="sap.m" xmlns:mvc="sap.ui.core.mvc" xmlns:core="sap.ui.core" xmlns:form="sap.ui.layout.form" xmlns:semantic="sap.m.semantic">
```

Required result:

```
<View controllerName="opensap.manageproducts.controller.Object" xmlns="sap.m"  
      xmlns:mvc="sap.ui.core.mvc" xmlns:core="sap.ui.core" xmlns:form="sap.ui.layout.form" 
      xmlns:semantic="sap.m.semantic">
```

Maybe you can make use of a global line length value in VS code?

Thanks for your work!

**Comment by FabianLauer** [comment]
Thank you for your input 😄 👍 

VS Code supports line wrapping out of the box. Just add this to your user preferences file:

``` json
"editor.wrappingColumn": 0
```

Setting the value to zero will make lines wrap at the right edge of the editor, any number greater than zero will make lines wrap at that column.
