### ISSUE TITLE
Attribute ending in backslash fails formatting

### ISSUE THREAD

**Issue by KarlGunderson** [FabianLauer/vs-code-xml-format#6]
An attribute like:

<absPath url="D:\Users\kgunders\Documents\MR\Projects\HyperLinkSheets\"

Will cause the following error:

XML formatting failed: at line 2, column 694: namespace prefix must be followed by a tag name.

Here is more context from the problematic XML:

```
    <Choice Requires="x15">
        <absPath url="D:\Users\kgunders\Documents\MR\Projects\HyperLinkSheets\" xmlns:x15ac="http://schemas.microsoft.com/office/spreadsheetml/2010/11/ac" />
    </Choice>
```

A work around is to temporarily add a character after the backslash, format, and remove the extra character.

**Comment by FabianLauer** [comment]
@KarlGunderson Thank you for this hint. I'm looking into it right now 👍

**Comment by FabianLauer** [comment]
This problem is now fixed in the XML library. There'll be an update for the extension soon 😃
