### ISSUE TITLE
Node containing a period fails formatting

### ISSUE THREAD

**Issue by blitzxion** [FabianLauer/vs-code-xml-format#7]
Almost like Issue #6. 

A node like

``` xml
<system.webServer>
<!-- .... -->
</system.webServer>
```

Will cause an error and will not format the document.

```
XML formatting failed: at line #, column #; expected whitespace or end of opening tag.
```

Work around would be to simply remove the period from the nodes, format the document, then add them back.

**Comment by FabianLauer** [comment]
Hi @blitzxion, thank you for reporting this 👍 
It's now fixed in the XML library. I'm still testing, but there'll be an update soon 😉
