### ISSUE TITLE
Formatting doesn't appear in Cmd+Shift+P menu

### ISSUE THREAD

**Issue by YvesR** [FabianLauer/vs-code-xml-format#8]
Hello,
I did install the extension on MAC OS X. Extension installed, restarted, but Cmd+Shift+P do not list "Format Code". Any clue?

Thanks, Yves

**Comment by FabianLauer** [comment]
Hi @YvesR,
thanks for the feedback. Currently, the extension is only active when the language mode is set to XML. You can set the mode using Cmd+Shift+P, then enter 'language mode' and select XML.
If it doesn't work then, feel free to reopen this issue 😄

**Comment by YvesR** [comment]
Thank you for your quick feedback. Yes, I just opened a clean file and copy paste some example xml in the new document. After Cmd+K+M+Xml it works like expected.
